### ISSUE TITLE
Make separate inventories for CB creative and other

### ISSUE THREAD

**Issue by NorbiPeti** [alisolarflare/CreativeBoundaries#12]
Save survival inventories to files when switching to cbgm1 and clear the player inventory. On cbgm0 load player inventory and delete the file. When the player gets on check for existing file and cbgm0 the player if the file exists (in case of a server crash or other weirdness).

Saving inventories should be relatively easy, as ItemStacks are ConfigurationSerializable - I'm still a bit usnure about how to make use of it though.

**Comment by alisolarflare** [comment]
This issue was moved to TBMCPlugins/AliPresents#6

**Comment by alisolarflare** [comment]
wrong issue

**Comment by alisolarflare** [comment]
wait right issue
